### ISSUE TITLE
createしたshm領域のremove実装について

### ISSUE THREAD

**Issue by jskhtakeda** [kyawawa/choreonoid_plugins#4]
実は現在の記述では，shmの領域をcreateした後，removeしていません．
createしたshmの領域をremoveする際には
shared_memory_object::remove
という関数を呼べばいいようなのですが，これをどこに記述すれば良いでしょうか？

現在，controller/PDController_InvertedPendulum.cppのコントローラはinitialize()とcontrol()関数をメンバ関数に持っていますが，そのうちcontrol()関数内でshmの領域を確保している状況です．

本来control()でなくinitialize()関数でshmのcreateをして，このコントローラのデストラクタ内でremoveする記述をしておけば良いのかと思いますが，うまくいきませんでした．

**Comment by kyawawa** [comment]
Pluginクラスには finalize という仮想関数があるからそれを使うと良さそう
適当にやってみた感じだとうまく行っている気がする
```c++
    virtual bool finalize() override
    {
        std::ofstream outfile ("/tmp/hoge.txt");
        outfile << "my text here!" << std::endl;
        outfile.close();
    }
```

**Comment by jskhtakeda** [comment]
pluginのinitialize()関数内でshmの領域をcreateし，finalize()関数内でremoveするようにしていきます．

**Comment by jskhtakeda** [comment]
[[plugins/OptimizeGainPlugin.cpp] Use sigSimulationFinished instead of reset timer #7](https://github.com/kyawawa/choreonoid_plugins/pull/7)
で解決していただきましたので，閉じます．
