### ISSUE TITLE
nloptのソルバをどこに記述するか

### ISSUE THREAD

**Issue by jskhtakeda** [kyawawa/choreonoid_plugins#9]
nloptはソルバのインスタンスを作って，そこに評価関数や制約を設定して，最後にソルバを実行する関数を呼ぶ，みたいな使い方だと思うのですが，
nloptに設定する評価関数の内部でシミュレーションをリセットして，シミュレーション終了時に評価値を返すみたいな設計にすれば簡単ではないでしょうか．

現在の実装のような，シミュレーションがリセットされるタイミングで何らかの関数を呼ぶ，という仕組みだと，ソルバをどのプロセスで回せばよいかわからないです．

**Comment by kyawawa** [comment]
nloptの使い方があまり分かってないのでちょっと判断しかねます．
最大限こっちでも見てみようと思いますが，とりあえず今回は自由にやってみてもらえればと思います．
実装で詰まったらまた聞いてください．

**Comment by kyawawa** [comment]
本日までで実装した僕の中での一応の結論としては，
1. NLoptのoptimizeを呼ぶためのスレッドを切る
1. コスト関数の最初でstartSimulationを(間接的に)呼ぶ
1. simulationTimeが設定した時間を超えるか，shared memoryに書き込まれたfinished判定(実質fail判定)がなされるまでsleepで待つ
1. shared memoryに書き込まれたcostをreturnする

といった感じになりました．
なので，

> nloptに設定する評価関数の内部でシミュレーションをリセットして，シミュレーション終了時に評価値を返すみたいな設計にすれば簡単ではないでしょうか．

これは正しかったのだと思います．参考になりました．ありがとう．

**Comment by jskhtakeda** [comment]
こちらこそ，いろいろ教えて頂いてありがとうございました．
この議題は解決したため閉じさせていただきます．
